apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-server
  labels:
    app: mysql-server
spec:
  template:
    metadata:
      labels:
        app: mysql-server
    spec:
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: volume
      containers:
      - name: mysql-server
        image: mysql:5.7
        args:
          - "--ignore-db-dir=lost+found"
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: configmap
              # Specify the key associated with the value
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: configmap
              # Specify the key associated with the value
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: MYSQL_ROOT_PASSWORD

        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mysql-volume
---
kind: Service
apiVersion: v1
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql-server
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306

